/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;

import clases.JPanelConFondo;
import clases.RegistroInicial;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Braya
 */
public class SeleccionVehiculo extends javax.swing.JFrame {

    RegistroInicial reg_ini;

    public SeleccionVehiculo() {
        initComponents();
        JPanelConFondo panelFondo = new JPanelConFondo("src/img/fondo.png");
        panelFondo.setBounds(0, 0, jpnlFondoImagen.getWidth(), jpnlFondoImagen.getHeight());
        jpnlFondoImagen.add(panelFondo);
        jpnlFondoImagen.setOpaque(false);
        jrbAuto.setActionCommand("Auto");
        jrbCamioneta.setActionCommand("Camioneta");
        jrbMoto.setActionCommand("Moto");
        bgVehiculos.add(jrbAuto);
        bgVehiculos.add(jrbCamioneta);
        bgVehiculos.add(jrbMoto);
        this.setLocationRelativeTo(null);
    }

    public void setRegistroIncial(RegistroInicial rt) {
        reg_ini = rt;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgVehiculos = new javax.swing.ButtonGroup();
        jpnlFondoImagen = new javax.swing.JPanel();
        jrbAuto = new javax.swing.JRadioButton();
        jrbMoto = new javax.swing.JRadioButton();
        jrbCamioneta = new javax.swing.JRadioButton();
        jbtSiguiente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlFondoImagen.setBackground(new java.awt.Color(59, 54, 47));
        jpnlFondoImagen.setPreferredSize(new java.awt.Dimension(570, 505));

        jrbAuto.setBackground(new java.awt.Color(59, 54, 47));
        bgVehiculos.add(jrbAuto);
        jrbAuto.setFont(new java.awt.Font("Racing Sans One", 0, 36)); // NOI18N
        jrbAuto.setForeground(new java.awt.Color(255, 255, 255));
        jrbAuto.setText("Auto");
        jrbAuto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jrbAuto.setBorderPainted(true);
        jrbAuto.setIconTextGap(15);
        jrbAuto.setInheritsPopupMenu(true);

        jrbMoto.setBackground(new java.awt.Color(59, 54, 47));
        bgVehiculos.add(jrbMoto);
        jrbMoto.setFont(new java.awt.Font("Racing Sans One", 0, 36)); // NOI18N
        jrbMoto.setForeground(new java.awt.Color(255, 255, 255));
        jrbMoto.setText("Moto");
        jrbMoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jrbMoto.setBorderPainted(true);
        jrbMoto.setIconTextGap(15);

        jrbCamioneta.setBackground(new java.awt.Color(59, 54, 47));
        bgVehiculos.add(jrbCamioneta);
        jrbCamioneta.setFont(new java.awt.Font("Racing Sans One", 0, 36)); // NOI18N
        jrbCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        jrbCamioneta.setText("Camioneta");
        jrbCamioneta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jrbCamioneta.setBorderPainted(true);
        jrbCamioneta.setIconTextGap(15);

        jbtSiguiente.setBackground(new java.awt.Color(167, 190, 56));
        jbtSiguiente.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jbtSiguiente.setText("siguiente");
        jbtSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSiguienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(249, 138, 7));

        rSLabelFecha1.setForeground(new java.awt.Color(0, 0, 0));

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Racing Sans One", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Vehículo");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Racing Sans One", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona el tipo de ");

        javax.swing.GroupLayout jpnlFondoImagenLayout = new javax.swing.GroupLayout(jpnlFondoImagen);
        jpnlFondoImagen.setLayout(jpnlFondoImagenLayout);
        jpnlFondoImagenLayout.setHorizontalGroup(
            jpnlFondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFondoImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlFondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFondoImagenLayout.createSequentialGroup()
                        .addComponent(jbtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFondoImagenLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFondoImagenLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(jpnlFondoImagenLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jpnlFondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(jrbMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jpnlFondoImagenLayout.setVerticalGroup(
            jpnlFondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFondoImagenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jrbAuto)
                .addGap(18, 18, 18)
                .addComponent(jrbCamioneta)
                .addGap(18, 18, 18)
                .addComponent(jrbMoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jbtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlFondoImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlFondoImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSiguienteActionPerformed
        ButtonModel selectedButton = bgVehiculos.getSelection();
        if (selectedButton != null) {
            String tipo_vehi = selectedButton.getActionCommand().toLowerCase();
            reg_ini.setTipo_vehiculo(tipo_vehi);
            SeleccionUbiPisoA pisoa = new SeleccionUbiPisoA();
            pisoa.setRegistroIncial(reg_ini);
            pisoa.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtSiguiente;
    private javax.swing.JPanel jpnlFondoImagen;
    private javax.swing.JRadioButton jrbAuto;
    private javax.swing.JRadioButton jrbCamioneta;
    private javax.swing.JRadioButton jrbMoto;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    // End of variables declaration//GEN-END:variables
}
